/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects and kept here so the
// scaffold type-checks once dependencies are installed.
